[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-serial = "5.4.0"
rtu-client = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.5", features = ["sqlite", "runtime-tokio-native-tls"] }
plotters = "0.3.1"
chrono = "0.4"
